# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    include:
      - master

resources:
  containers:
    - container: server_builder
      image: hasura/graphql-engine-server-builder:20190314

jobs:
  - job: build_server
    pool:
      vmImage: 'ubuntu-16.04'
    container: server_builder
    steps:
      - checkout: self
        clean: true
      - bash: |
          build_output=$BUILD_OUTPUT BUILD_FLAGS="--fast --coverage" make ci-binary
        workingDirectory: $(Build.Repository.LocalPath)/server
        displayName: Running non-optimized build with coverage
        condition: in(variables['Build.Reason'], 'PullRequest')
        env:
          BUILD_OUTPUT: $(Build.ArtifactStagingDirectory)/server_output
      - bash: |
          build_output=$BUILD_OUTPUT make ci-binary
        workingDirectory: $(Build.Repository.LocalPath)/server
        displayName: Running optimized build with coverage
        condition: in(variables['Build.Reason'], 'IndividualCI', 'Manual')
        env:
          BUILD_OUTPUT: $(Build.ArtifactStagingDirectory)/server_output
      - bash: |
          build_output=$BUILD_OUTPUT make ci-image
          build_output=$BUILD_OUTPUT make ci-save-image
        workingDirectory: $(Build.Repository.LocalPath)/server
        displayName: Build docker image and save to artifacts folder
        env:
          BUILD_OUTPUT: $(Build.ArtifactStagingDirectory)/server_output
