# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
    - container: server_builder
      image: hasura/graphql-engine-server-builder:20190314

jobs:
  - job: build_server
    pool:
      vmImage: 'ubuntu-16.04'
    container: server_builder
    steps:
      - checkout: self
        clean: true